services:
  app:
    build: .
    container_name: fastapi-starter
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      ENV: "development"
      HOST: "0.0.0.0"
      PORT: "8000"
      RELOAD: "true"
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --reload
