blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation guidelines
    url: https://github.com/your-username/sprint-assistant/issues/new?template=documentation.md
    about: Report or suggest improvements to documentation
